<?php

namespace AppBundle\Repository;
use Symfony\Component\HttpFoundation\Request;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{

}
