security:
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
    providers:
            in_memory:
                memory:
                    users:
                        fred:
                            password: fred
                            roles: 'ROLE_USER'
                        admin:
                            password: admin
                            roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    access_control:
            # require ROLE_ADMIN for /admin*
          - { path: ^/, roles: ROLE_USER }